### PR TITLE
Not sure why but re-running lint still returns a bunch of errors

### PR DESCRIPTION
**Pull request by cadrianxyz**
consistent styling must be set up from the start - quite very important

### CODE REVIEW

**Comment by cadrianxyz** [comment]
@kraytaps merge asap!!

**Review by kraytaps — APPROVED** [review]

**Comment by kraytaps** [comment]
there are errors??

**Comment by cadrianxyz** [comment]
eh warnings not errors

**Comment by cadrianxyz** [comment]
Screen Shot 2020-03-10 at 10 23 29 AM
this brings me so much joy

**Pull request merged**
