### PR TITLE
Mixins

### LINKED ISSUE #13: [Rework] Abstract SCSS using mixins
### Purpose of Enhancement
* there's a lot of repetition

#### Additional Notes
- [x] create new mixins
- [x] prepend in sass-loader

### PR DESCRIPTION
**Pull request by kraytaps**
# Description

Created mixins file and prepended it to all sass files for future use. Currently only one mixin is actually in use.

Fixes #13 

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] Code follows the project's style guidelines
- [x] I have performed a self-review of the Code being pushed
- [ ] Code has been reviewed by at least one other developer
- [x] Code has appropriate commenting, particularly in hard-to-understand areas
- [x] Corresponding changes to the documentation have been made
- [x] The changes generate no new warnings

### CODE REVIEW

**Comment by cadrianxyz** [comment]
There aren't '@media' stuff you think can be turnt into mixins ya?

**Comment by kraytaps** [comment]
hmm i don't think so, btw usually people use max-width if they're designing desktop first, and min-width if they're designing mobile first

**Comment by kraytaps** [comment]
i think we should use min width for media queries here on out

**Comment by cadrianxyz** [comment]
noted. start an issue if you think previous method needs refactoring

**Review by cadrianxyz — APPROVED** [review]

**Pull request merged**
